# Generated by Django 4.1 on 2022-08-10 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('slot_1', models.IntegerField(max_length=1000)),
                ('slot_2', models.IntegerField(max_length=1000)),
                ('slot_3', models.IntegerField(max_length=1000)),
                ('slot_4', models.IntegerField(max_length=1000)),
                ('slot_5', models.IntegerField(max_length=1000)),
                ('slot_6', models.IntegerField(default=25, max_length=1000)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
