# Generated by Django 4.1 on 2022-08-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slot_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='slot_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='slot_3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='slot_4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='slot_5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='slot_6',
            field=models.IntegerField(default=25),
        ),
    ]
